version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install

  build:
    commands:
      - echo Build started on `date`
      - npm run build || echo No build script found

  post_build:
    commands:
      - echo Packaging application...
      - zip -r app.zip . -x node_modules/\*

artifacts:
  files:
    - app.zip
